# Generated by Django 6.0.7 on 2026-07-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('file', 'File'), ('rating', 'Rating')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.formversion')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='fields.field')),
            ],
        ),
    ]
