# Generated by Django 6.0.7 on 2026-07-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='fieldoption',
            options={'ordering': ['display_order']},
        ),
    ]
