import { motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, ClipboardList, FileDown, LineChart, LockKeyhole, Menu, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import heroLandscape from "@/assets/formcraft-hero-landscape.png";

const reveal = {
  hidden: { opacity: 0, y: 26 },
  show: (delay = 0) => ({ opacity: 1, y: 0, transition: { delay, duration: 0.85, ease: [0.16, 1, 0.3, 1] } }),
};

export default function LandingReference() {
  return (
    <main className="bg-[#f1f0ea] text-[#20241f]">
      <section className="relative min-h-[760px] overflow-hidden bg-white px-3 pb-0 pt-3 sm:px-5 sm:pt-5 lg:min-h-[760px]">
        <div className="absolute inset-x-3 top-[67px] h-[570px] overflow-hidden rounded-[22px] sm:inset-x-5 sm:top-[74px] sm:h-[620px]"><img src={heroLandscape} alt="Abstract green landscape" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(16,28,20,.68),rgba(16,28,20,.16)_60%,rgba(8,16,11,.22))]" /></div>
        <nav className="relative z-10 mx-auto flex max-w-[1440px] items-center justify-between bg-white px-2 py-3 text-sm sm:px-3">
          <Link to="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid size-5 place-items-center rounded-md bg-emerald-500 text-[8px] text-white">FC</span> FormCraft</Link>
          <div className="hidden items-center gap-8 text-[11px] font-medium text-slate-600 md:flex"><a href="#platform" className="transition hover:text-emerald-600">Home</a><a href="#platform" className="transition hover:text-emerald-600">About</a><a href="#how-it-works" className="transition hover:text-emerald-600">Features</a><a href="#services" className="transition hover:text-emerald-600">Services</a><a href="#security" className="transition hover:text-emerald-600">Contact</a></div>
          <div className="flex items-center gap-2"><Link to="/login" className="hidden rounded-full border border-slate-200 px-4 py-2 text-[11px] font-semibold text-slate-700 transition hover:border-emerald-500 hover:text-emerald-600 sm:block">Log in</Link><Link to="/register" className="hidden rounded-full bg-emerald-500 px-4 py-2 text-[11px] font-semibold text-white shadow-sm shadow-emerald-500/30 transition hover:bg-emerald-600 sm:block">Get Started</Link><button type="button" aria-label="Open navigation" className="grid size-9 place-items-center rounded-full border border-slate-200 text-slate-700 md:hidden"><Menu className="size-4" /></button></div>
        </nav>
        <div className="relative z-10 mx-auto flex min-h-[570px] max-w-[1440px] flex-col justify-center px-10 pb-16 pt-24 sm:min-h-[620px] sm:px-14 lg:px-20">
          <motion.p initial="hidden" animate="show" variants={reveal} className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.17em] text-[#e5f86f]"><Sparkles className="size-3.5" /> The modern form builder</motion.p>
          <motion.h1 initial="hidden" animate="show" custom={0.1} variants={reveal} className="mt-5 max-w-4xl text-5xl font-medium leading-[.91] tracking-[-.065em] text-white sm:text-7xl lg:text-[76px]">Build smarter<br />forms for every workflow.</motion.h1>
          <motion.div initial="hidden" animate="show" custom={0.2} variants={reveal} className="mt-7 flex flex-col gap-5 border-t border-white/35 pt-5 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-sm text-sm leading-6 text-white/80">Create powerful forms with validation, conditional logic, publishing, and response management—all in one place.</p><div className="flex gap-5"><Link to="/register" className="group flex w-fit items-center gap-2 border-b border-white/60 pb-2 text-xs font-bold text-white transition hover:border-[#e5f86f]">Get Started <ArrowUpRight className="size-3.5 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></Link><a href="#how-it-works" className="group flex w-fit items-center gap-2 border-b border-white/60 pb-2 text-xs font-bold text-white transition hover:border-[#e5f86f]">Explore Features <ArrowUpRight className="size-3.5 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></a></div></motion.div>
          <motion.div initial={{ opacity: 0, x: 22 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.55, duration: 0.7 }} className="absolute right-12 top-20 hidden w-56 rounded-2xl bg-white/25 p-4 text-white backdrop-blur-md lg:block"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-white/65">Conditional Logic</p><div className="mt-4 space-y-2 rounded-xl bg-white/12 p-3 text-xs"><p className="font-semibold">Age</p><p className="rounded-md bg-white/10 px-2 py-1.5 text-white/80">Greater than&nbsp;&nbsp; 18</p><p className="pt-1 text-center text-emerald-200">↓</p><p className="font-semibold">Driving License</p></div><Link to="/register" className="mt-4 flex items-center gap-2 text-[11px] font-bold"><span className="grid size-7 place-items-center rounded-full border border-white/40"><ArrowUpRight className="size-3" /></span> Open FormCraft</Link></motion.div>
        </div>
        <motion.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .55, duration: .7 }} className="relative z-20 ml-auto -mt-24 grid w-full max-w-[640px] grid-cols-3 bg-white p-7 text-[#20241f] shadow-xl sm:p-8"><Stat value="10+" label="flexible field types" /><Stat value="5" label="validation rules" /><Stat value="∞" label="conditional logic" /></motion.div>
      </section>

      <section id="platform" className="mx-auto grid max-w-[1260px] gap-10 px-6 py-20 sm:px-10 lg:grid-cols-[1.1fr_.9fr] lg:px-14 lg:py-28"><motion.div initial="hidden" whileInView="show" viewport={{ once: true, amount: .25 }} variants={reveal}><h2 className="max-w-2xl text-4xl font-medium leading-[.98] tracking-[-.055em] sm:text-5xl">Built for simplicity, <span className="text-slate-400">designed for control.</span></h2></motion.div><div className="self-end text-sm leading-6 text-slate-600">FormCraft gives you everything needed to create reliable forms without unnecessary complexity. From field configuration to submission management, everything stays in one place.</div><div className="col-span-full mt-4 flex flex-wrap justify-center gap-3 sm:gap-5">{["Form Builder", "Validation", "Conditional Logic", "Publishing", "Responses"].map((label, i) => <motion.div key={label} whileHover={{ y: -6, scale: 1.03 }} className={`grid size-28 place-items-center rounded-full text-center text-xs font-semibold shadow-sm sm:size-36 ${i === 0 ? "bg-white text-[#25a86d] ring-1 ring-slate-200" : "bg-[#e9ebe6] text-slate-700"}`}>{label}</motion.div>)}</div></section>
      <FeatureGrid />
      <Services />
      <CaseStudy />
      <section id="security" className="mx-auto max-w-[1440px] px-6 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="grid overflow-hidden bg-[#263829] text-white lg:grid-cols-[1.1fr_.9fr]"><div className="p-8 sm:p-12"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#dff46e]">Designed with intention</p><h2 className="mt-6 max-w-lg text-4xl font-medium leading-[.98] tracking-[-.055em] sm:text-5xl">The work behind every meaningful response.</h2><p className="mt-6 max-w-md text-sm leading-6 text-white/70">Keep your team aligned, your data considered, and your next decision in view.</p><Link to="/register" className="mt-9 inline-flex items-center gap-8 bg-[#e5f86f] px-4 py-3 text-xs font-bold text-[#1d2a1f] transition hover:bg-white">Start for free <ChevronRight className="size-4" /></Link></div><div className="flex min-h-72 items-end bg-[linear-gradient(135deg,#6a8056_0%,#374b34_45%,#1e2c22_100%)] p-8 sm:p-12"><div className="grid w-full grid-cols-2 border border-white/20 text-sm"><div className="border-r border-white/20 p-5"><p className="text-3xl font-medium tracking-tight">100%</p><p className="mt-2 text-xs text-white/65">your form control</p></div><div className="p-5"><Check className="size-6 text-[#e5f86f]" /><p className="mt-5 text-xs text-white/65">built for clarity</p></div></div></div></div></section>
      <footer className="mx-auto flex max-w-[1440px] flex-col gap-4 border-t border-[#cbcec3] px-6 py-8 text-xs text-slate-500 sm:flex-row sm:justify-between sm:px-10 lg:px-14"><span className="font-bold text-[#20241f]">FormCraft</span><span>© {new Date().getFullYear()} FormCraft</span></footer>
    </main>
  );
}

function Stat({ value, label }) { return <div className="border-r border-slate-200 px-6 last:border-0"><p className="text-4xl font-medium tracking-[-.06em]">{value}</p><p className="mt-1 max-w-[105px] text-[11px] leading-4 text-slate-500">{label}</p></div>; }

function FeatureGrid() { const features = [[ShieldCheck, "Layered security", "Protect forms and response data with deliberate access controls."], [Check, "Built for quality", "A clear, considered experience from first question to export."], [MessageCircle, "Reliable support", "Keep each workflow moving with dependable tools at every step."], [ClipboardList, "Simple form building", "Everything your team needs in one visual workspace."], [FileDown, "Exports without friction", "Take your response data wherever the next decision happens."], [LineChart, "Insight at a glance", "See completion and answer trends as they unfold."]]; return <section className="bg-[#e8eae5] px-6 py-20 sm:px-10"><div className="mx-auto max-w-[1100px]"><h2 className="mx-auto max-w-xl text-center text-4xl font-medium leading-[.98] tracking-[-.055em] sm:text-5xl">We offer clarity, <span className="text-slate-400">with the tools that make responses useful.</span></h2><div className="mt-10 grid overflow-hidden rounded-xl border border-slate-200 bg-white sm:grid-cols-3">{features.map(([Icon, title, text], index) => <motion.article key={title} initial="hidden" whileInView="show" viewport={{ once: true }} custom={index * .06} variants={reveal} className="min-h-44 border-b border-r border-slate-200 p-6 last:border-b-0 sm:[&:nth-last-child(-n+3)]:border-b-0"><span className="grid size-8 place-items-center rounded-lg bg-emerald-50 text-emerald-600"><Icon className="size-4" /></span><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></motion.article>)}</div></div></section>; }

function Services() { const services = [["01", "Draft in minutes"], ["02", "Guide with logic"], ["03", "Review every response"], ["04", "Export with confidence"]]; return <section className="mx-auto grid max-w-[1260px] gap-10 px-6 py-20 sm:px-10 lg:grid-cols-2 lg:px-14 lg:py-28"><div><h2 className="max-w-md text-4xl font-medium leading-[.98] tracking-[-.055em] sm:text-5xl">A trusted workflow, <span className="text-slate-400">for every kind of question.</span></h2><Link to="/register" className="mt-7 inline-flex items-center gap-2 rounded-full bg-emerald-500 px-4 py-2.5 text-xs font-bold text-white">Get started <ArrowUpRight className="size-3.5" /></Link><div className="mt-16 grid max-w-md grid-cols-2 gap-3">{services.map(([number, title]) => <div key={number} className="rounded-xl border border-slate-200 p-4"><p className="text-xs text-slate-400">{number}</p><p className="mt-4 text-sm font-medium">{title}</p><a href="#platform" className="mt-4 block text-[11px] font-semibold underline">View details</a></div>)}</div></div><div className="relative min-h-[440px] overflow-hidden rounded-2xl bg-[linear-gradient(145deg,#c7d4b3,#6a8663_50%,#314638)]"><motion.div animate={{ y: [0, -9, 0] }} transition={{ duration: 4.5, repeat: Infinity }} className="absolute right-7 top-7 w-52 rounded-xl border border-white/40 bg-white/80 p-4 backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">New form</p><p className="mt-3 text-lg font-semibold">Customer pulse</p><div className="mt-5 h-2 rounded bg-slate-200"><div className="h-full w-2/3 rounded bg-emerald-500" /></div><p className="mt-2 text-[10px] text-slate-500">3 of 5 questions ready</p></motion.div><div className="absolute bottom-7 left-7 rounded-xl bg-[#203427] p-5 text-white"><p className="text-xs text-white/60">Designed for focus</p><p className="mt-2 max-w-40 text-lg font-medium leading-5">Every question earns its place.</p></div></div></section>; }

function CaseStudy() { return <section className="px-6 py-20 sm:px-10"><h2 className="mx-auto max-w-lg text-center text-4xl font-medium leading-[.98] tracking-[-.055em] sm:text-5xl">See how teams solve problems, <span className="text-slate-400">right from the response.</span></h2><motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={reveal} className="mx-auto mt-12 grid max-w-[1100px] overflow-hidden rounded-2xl bg-[#edf0ea] md:grid-cols-2"><div className="p-8 sm:p-10"><p className="text-lg font-semibold">FormCraft teams</p><blockquote className="mt-7 max-w-md text-sm leading-6 text-slate-700">“We can now build, share, and understand feedback without turning every request into a process. FormCraft gives every team a clearer next step.”</blockquote><Link to="/register" className="mt-7 inline-flex rounded-full bg-emerald-500 px-4 py-2.5 text-xs font-bold text-white">Build your workflow</Link><p className="mt-14 text-xs"><strong>Every team</strong> — working with better signals</p></div><div className="flex min-h-72 items-end bg-[radial-gradient(circle_at_70%_20%,#c7e0d1,transparent_34%),linear-gradient(140deg,#93ad8c,#405b43)] p-7"><div className="w-full rounded-xl bg-white/90 p-5 shadow-lg"><p className="text-xs font-semibold">Response dashboard</p><div className="mt-5 flex h-16 items-end gap-1">{[34, 49, 42, 80, 60, 94, 72, 100].map((h, i) => <motion.span key={i} initial={{ height: 0 }} whileInView={{ height: `${h}%` }} viewport={{ once: true }} transition={{ delay: i * .06 }} className="flex-1 rounded-t bg-emerald-500" />)}</div></div></div></motion.div></section>; }
