# Generated by Django 6.0.7 on 2026-07-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='formversion',
            unique_together={('form', 'version')},
        ),
    ]
