# Generated by Django 6.0.7 on 2026-08-06 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_field_options_alter_fieldoption_options'),
        ('forms', '0004_formversion_share_token_formversion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionalrule',
            name='rule',
        ),
        migrations.AddField(
            model_name='conditionalrule',
            name='action',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('require', 'Require')], default='show', max_length=20),
        ),
        migrations.AddField(
            model_name='conditionalrule',
            name='comparison_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionalrule',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('greater_than', 'Greater Than'), ('is_empty', 'Is Empty')], default='equals', max_length=30),
        ),
        migrations.AddField(
            model_name='conditionalrule',
            name='target_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_rules', to='fields.field'),
        ),
        migrations.AddField(
            model_name='conditionalrule',
            name='trigger_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to='fields.field'),
        ),
    ]
