# Generated by Django 6.0.7 on 2026-08-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_milestone3_submission_tracking_audit_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
