# Generated by Django 6.0.7 on 2026-08-24 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_onetimetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='limit_one_submission_per_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='require_email_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='respondent_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('verification_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='forms.form')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
